---
title: "Function"
output: html_notebook
---

```{r}
library(tidyverse)
library(rlang)
library(lobstr)
```

# Table_join

`*_join`

argument `by = c("Name.x" = "Name.y")` is named length 1 chr vector
where `Name.x` is name of `"Name.y"`

```{r}
lobstr::ast(by <- c("Name" = "user_full_name"))
```


```{r}
table_join <- function(fun, df.lt, df.rt, key.lt = NULL , key.rt = NULL,  ...){
  
 fun  <- switch (fun,
    "semi_join" = semi_join,
    "anti_join" = anti_join,
    "inner_join" = inner_join,
    "left_join" = left_join,
    "right_join" = right_join,
    "full_join" =full_join,
    stop("This function is not supported", call. = F)
    )

  names(key.rt) <- key.lt 
  
  call2(fun, df.lt, df.rt, key.rt, ...) %>% eval()

}

table_join("left_join", band_instruments, band_instruments2, 
             key.lt = "name", key.rt = "artist", suffix = c("_inst1", "_inst2"))
```
```{r}
table_join("anti_join", ids, elect, key.lt = "Name", key.rt = "user_full_name")
```
```{r}
table_join("left_join", band_members, band_instruments)
```



```{r}
by <-  c("Name" = "user_full_name")
by
c("Name" = "user_full_name") %>% names()
```

```{r}
table_join("left_join", ids, elect, by = c("Name" = "user_full_name"))
```

```{r}
table_join("left_join", band_instruments, band_members, by = c("df"))
```


# Swab

Don't work in shiny
```{r}
swab <- function(x,y) {
  a <- x
  b <- y
  
  y <<- a
  x <<- b
}
```

```{r}
x <- c(1:10)
y <- c(letters[1:10])

swab(x,y)
x
y
```

```{r}
my_l <- list(x, y)

swab_l <- function(list) {
  
  rev(list)

}

rev(my_l)
swab_l(my_l)

my_l %>% setNames(c("y","x"))
```

```{r}
odd <- seq(1,10, by = 2) 
even <- seq(2,10, by = 2)

odd %% 2
all(even %% 2 == 0)
```

# Distinct

```{r}
distinct2 <- function(df, vars, ...) {
  vars <- syms(vars)
  df %>% 
    distinct(!!!vars, ...)
}
```


```{r}
left_join(ids, elect, by = c("Name" = "user_full_name")) %>% 
  distinct2(c("No","ID"))
```

```{r}
left_join(ids, elect, by = c("Name" = "user_full_name")) %>% 
  count(across(everything()), sort = T)
```

## Distinct or Count

```{r remove_dup}
remove_dup <- function(df, vars ,all_vars = F, type = "distinct",  ...) {
  
  fun <- switch (type,
    "distinct" = distinct,
    "count" = count
     )
  
  if(all_vars) return( fun(df, across(names(df))) )
  
  vars <- syms(vars)
  
  df %>% fun(!!!vars, ...)
}
```

```{r}
dat <- left_join(ids, elect, by = c("Name" = "user_full_name")) %>% 
  filter(ID == "6201092", ip_address == "10.7.51.177", time == "18/11/20, 12:45") 

dat %>% distinct(NULL)
dat %>% remove_dup("origin",type = "count")
```

```{r}
logic <- T

switch (logic,TRUE =="count", FALSE =="distinct") # Don't work

if(logic){"count"}else{"distinct"} 
```


### Images

Resolution
2398 × 1800
```{r}
c(2398, 1800) / 2
c(2398, 1800) / 3
```

